name: ASP.NET Core CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'
      
    # Build with dotnet in the project's directory
    - name: Build with dotnet
      run: dotnet build --configuration Release NZWalks.API/NZWalks.API.csproj
