name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Actions'
      uses: actions/checkout@v2

    - name: 'Set up .NET Core'
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'  # Adjust to match your .NET version

    - name: 'Restore Dependencies'
      run: dotnet restore

    - name: 'Build the API'
      run: dotnet build --configuration Release --no-restore

    - name: 'Publish the API'
      run: dotnet publish -c Release -o ./publish_output
